name: Android Build AAB

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bundleRelease

      - name: Sign Android release AAB
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release/
          signingKeyBase64: ${{ secrets.KEYSTORE_FILE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "35.0.0"

      - name: Display structure of build files
        run: ls -R

      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v4.4.0
        with:
          name: Contacts-signed-aab-1.0.${{ github.run_number }}
          path: app/build/outputs/bundle/release/*.aab

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download AAB from build
        uses: actions/download-artifact@v4.1.8
        with:
          name: Contacts-signed-aab-1.0.${{ github.run_number }}
          path: app/build/outputs/bundle/release/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Release AAB
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app/build/outputs/bundle/release/Contacts-signed-aab-1.0.${{ github.run_number }}.aab
          asset_name: Contacts-signed-aab-1.0.${{ github.run_number }}.aab
          asset_content_type: application/octet-stream
