name: Android Build APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: ZipAlign & Sign Android release
        uses: kevin-david/zipalign-sign-android-release@v2.0.1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release/
          signingKeyBase64: ${{ secrets.KEYSTORE_FILE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          zipAlign: true
        env:
          BUILD_TOOLS_VERSION: "35.0.0"

      - name: Display structure of build files
        run: ls -R

      - name: Delete temp unaligned
        run: |
          rm "app/build/outputs/apk/release/Contacts-1.0.${{ github.run_number }}.apk.unaligned"

      - name: Delete temp idsig
        run:  |
          rm  "app/build/outputs/apk/release/Contacts-1.0.${{ github.run_number }}-signed.apk.idsig"

      - name: Delete temp keys
        run:  |
          rm  "app/build/outputs/apk/release/signingKey.jks"

      - name: Delete temp
        run:  |
          rm "app/build/outputs/apk/release/Contacts-1.0.${{ github.run_number }}.apk"

      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v4.4.0
        with:
          name: Contacts-signed-1.0.${{ github.run_number }}
          path: app/build/outputs/apk/release/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Display structure of downloaded files
        run: ls -R

      - name: Download APK from build
        uses: actions/download-artifact@v4.1.8
        with:
          name: Contacts-signed-1.0.${{ github.run_number }}
          path: app/build/outputs/apk/release/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Display structure of downloaded files
        run: ls -R

      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app/build/outputs/apk/release/Contacts-1.0.${{ github.run_number }}-signed.apk
          asset_name: Contacts-1.0.${{ github.run_number }}-signed.apk
          asset_content_type: application/zip
